<?php

namespace AppBundle\Entity;

/**
 * CertificateFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertificateFileRepository extends \Doctrine\ORM\EntityRepository
{
}
