<?php

namespace AppBundle\Entity;

/**
 * ImprovementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImprovementRepository extends \Doctrine\ORM\EntityRepository
{
}
